#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$MAIN_DB_USER" --dbname "$MAIN_DB_NAME" <<-EOSQL
    CREATE USER $BACKEND_APP_DB_USER WITH PASSWORD '$BACKEND_APP_DB_PASSWORD';
    GRANT CONNECT ON DATABASE $MAIN_DB_NAME TO $BACKEND_APP_DB_USER;
    GRANT USAGE ON SCHEMA public TO $BACKEND_APP_DB_USER;
    GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO $BACKEND_APP_DB_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
         GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $BACKEND_APP_DB_USER;	
EOSQL
